
(define-library (turtle simple)
  (import (turtle turtle3)
          (scheme base))
  (export forward back right left)
  (begin
    (define t (turtle-init))
    (define (forward dist)
      (forward! t dist))
    (define (back dist)
      (back! t dist))
    (define (right theta)
      (right! t theta))
    (define (left theta)
      (left! t theta))
    (define (up)
      (pen-up! t))
    (define (down)
      (pen-down! t))))
