
(define-library (turtle simple)
  (import (turtle turtle3)
          (scheme base))
  (export forward back right left up down)
  (begin
    (define t (turtle-init))
    (define (forward dist)
      (forward! t dist))
    (define (back dist)
      (forward! t (- dist)))
    (define (right theta)
      (yaw! t theta))
    (define (left theta)
      (yaw! t (- theta)))
    (define (up)
      (pen-up! t))
    (define (down)
      (pen-down! t))))
