
(import (turtle turtle3)
        (scheme base))

(define (cube t size)
  (let loop ((i 0))
    (when (< i 4)
      (let loop ((j 0))
        (when (< j 4)
          (forward! t size)
          (yaw! t 90)
          (loop (+ j 1))))
      (pitch! t 90)
      (forward! t size)
      (pitch! t -90)
      (roll! t -90)
      (loop (+ i 1)))))

(define (circle3d t radius)
  (define circum (* radius 6.283185307))
  (define start-orient (get-orient t))
  (define start-pos (get-pos t))
  (let loop ((i 0))
    (when (< i 120)
      (forward! t (/ circum 120))
      (pitch! t -3)
      (loop (+ i 1))))
  (apply set-orient! t start-orient)
  (set-pos! t start-pos))

(define (sphere t radius)
  (let loop ((i 0))
    (when (< i 20)
      (circle3d t radius)
      (yaw! t 9)
      (loop (+ i 1)))))

(define (helix t size)
  (let loop ((i 0))
    (when (< i 80)
      (forward! t (/ size 7))
      (yaw! t 10)
      (pitch! t 20)
      (loop (+ i 1)))))

(define (tetrahedron t size)
  (let loop ((i 0))
    (when (< i 3)
      (let loop ((j 0))
        (when (< j 3)
          (forward! t size)
          (yaw! t 120)
          (loop (+ j 1))))
      (yaw! t 60)
      (roll! t 109.47122063449069)
      (loop (+ i 1)))))

(define me (turtle-init))
(nutate! me)

;(cube me 100)
(sphere me 100)
;(helix me 100)
;(tetrahedron me 140)

